version: '2'

services:
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - media-root:/code/bakerydemo/media
    ports:
      - "8000:8000"
volumes:
  media-root:
