# Generated by Django 4.0.7 on 2022-08-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_sometext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sometext',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Some Texts'},
        ),
    ]
